/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asif siddique
 */
public class NewJFrame extends javax.swing.JFrame {

    
    String firstnumber;
    String secondnumber;
    String result;
    int a;
    int b;
    int b1=0;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seven = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Point = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Into = new javax.swing.JButton();
        one12 = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        Equalto = new javax.swing.JButton();
        Devide = new javax.swing.JButton();
        Square = new javax.swing.JButton();
        Root = new javax.swing.JButton();
        Clearscreen = new javax.swing.JButton();
        Delet = new javax.swing.JButton();
        display = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Seven.setBackground(java.awt.Color.lightGray);
        Seven.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Seven.setForeground(new java.awt.Color(0, 0, 101));
        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });

        Six.setBackground(java.awt.Color.lightGray);
        Six.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Six.setForeground(new java.awt.Color(0, 0, 101));
        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });

        Eight.setBackground(java.awt.Color.lightGray);
        Eight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Eight.setForeground(new java.awt.Color(0, 0, 101));
        Eight.setText("8");
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });

        Nine.setBackground(java.awt.Color.lightGray);
        Nine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Nine.setForeground(new java.awt.Color(0, 0, 101));
        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });

        Four.setBackground(java.awt.Color.lightGray);
        Four.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Four.setForeground(new java.awt.Color(0, 0, 101));
        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });

        Five.setBackground(java.awt.Color.lightGray);
        Five.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Five.setForeground(new java.awt.Color(0, 0, 101));
        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });

        Point.setBackground(java.awt.Color.lightGray);
        Point.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Point.setForeground(new java.awt.Color(0, 0, 101));
        Point.setText(".");
        Point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PointActionPerformed(evt);
            }
        });

        Two.setBackground(java.awt.Color.lightGray);
        Two.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Two.setForeground(new java.awt.Color(0, 0, 101));
        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });

        Three.setBackground(java.awt.Color.lightGray);
        Three.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Three.setForeground(new java.awt.Color(0, 0, 101));
        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });

        Zero.setBackground(java.awt.Color.lightGray);
        Zero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Zero.setForeground(new java.awt.Color(0, 0, 101));
        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });

        Into.setBackground(java.awt.Color.lightGray);
        Into.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Into.setForeground(new java.awt.Color(0, 0, 101));
        Into.setText("*");
        Into.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntoActionPerformed(evt);
            }
        });

        one12.setBackground(java.awt.Color.lightGray);
        one12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        one12.setForeground(new java.awt.Color(0, 0, 101));
        one12.setText("1");
        one12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one12ActionPerformed(evt);
            }
        });

        Minus.setBackground(java.awt.Color.lightGray);
        Minus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Minus.setForeground(new java.awt.Color(0, 0, 101));
        Minus.setText("-");
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });

        Plus.setBackground(java.awt.Color.lightGray);
        Plus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Plus.setForeground(new java.awt.Color(0, 0, 101));
        Plus.setText("+");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });

        Equalto.setBackground(java.awt.Color.lightGray);
        Equalto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Equalto.setForeground(new java.awt.Color(0, 0, 101));
        Equalto.setText("=");
        Equalto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualtoActionPerformed(evt);
            }
        });

        Devide.setBackground(java.awt.Color.lightGray);
        Devide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Devide.setForeground(new java.awt.Color(0, 0, 101));
        Devide.setText("/");
        Devide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevideActionPerformed(evt);
            }
        });

        Square.setBackground(java.awt.Color.lightGray);
        Square.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Square.setForeground(new java.awt.Color(0, 0, 101));
        Square.setText("x^2");
        Square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareActionPerformed(evt);
            }
        });

        Root.setBackground(java.awt.Color.lightGray);
        Root.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Root.setForeground(new java.awt.Color(0, 0, 101));
        Root.setText("ROOT");
        Root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RootActionPerformed(evt);
            }
        });

        Clearscreen.setBackground(java.awt.Color.lightGray);
        Clearscreen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Clearscreen.setForeground(new java.awt.Color(0, 0, 101));
        Clearscreen.setText("C");
        Clearscreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearscreenActionPerformed(evt);
            }
        });

        Delet.setBackground(java.awt.Color.lightGray);
        Delet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Delet.setForeground(new java.awt.Color(0, 0, 101));
        Delet.setText("Abs");
        Delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletActionPerformed(evt);
            }
        });

        display.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("         BASIC CALCULATOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Point, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Equalto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Root, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Square, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Clearscreen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Devide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Four, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Six, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Into, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(one12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Two, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Three, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Square, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Root, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Delet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Clearscreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Devide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Four, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Six, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Into, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Two, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Three, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Point, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equalto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jLabel1.getAccessibleContext().setAccessibleName("                BASIC CALCULATOR");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntoActionPerformed
        firstnumber = display.getText();
        display.setText("");
        //Equalto.setText(Equalto.getText()+ "+");
        a=3;
    }//GEN-LAST:event_IntoActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        firstnumber = display.getText();
        display.setText("");
        //Equalto.setText(Equalto.getText()+ "+");
        a=2;
    }//GEN-LAST:event_MinusActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
        String one = display.getText();
        display.setText(one + "0");
        //Equalto.setText(Equalto.getText()+ "0");
    }//GEN-LAST:event_ZeroActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        
        firstnumber = display.getText();
        display.setText("");
        //Equalto.setText(Equalto.getText()+ "+");
        a=1;
        
        
    }//GEN-LAST:event_PlusActionPerformed
//========================================================================================================================================================
    
    
    
    
    
    private void EqualtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualtoActionPerformed
       
        double first = Double.parseDouble(firstnumber);    
        double res=0;
        if(a<5){
        secondnumber = display.getText();
        
        //Equalto.setText(Equalto.getText()+"+"+ secondnumber+ "+");
        
        //double first=Double.parseDouble(firstnumber);
        double second=Double.parseDouble(secondnumber);

        
        
                if(a==1)
        {
            res=first+second;
        }
        else if(a==2)
        {
            res=first-second;
        }
        else if(a==3)
        {
            res=first*second;
        }
        else if(a==4)
        {
            res=first/second;
        }
        }
        
        
        
        
        else if(a==5)
        {
          //  double first=Double.parseDouble(firstnumber);
            //double res=0;
            res=first*first;
        }
        else if(a==6)
        {
            //double first = Double.parseDouble(firstnumber);
            
            res = Math.sqrt(first);
            
        }
        else if(a==7)
        {
            
            res=Math.abs(first);
        }

       
        
        String s = String.valueOf(res);
        display.setText(s);
        //Equalto.setText(Equalto.getText()+"="+ s);
        
        
    }//GEN-LAST:event_EqualtoActionPerformed

    
    
    
    //=====================================================================================================================================================
    private void DevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevideActionPerformed
        firstnumber = display.getText();
        display.setText("");
        //Equalto.setText(Equalto.getText()+ "+");
        a=4;
    }//GEN-LAST:event_DevideActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void RootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RootActionPerformed
        firstnumber= display.getText();
        display.setText("");
        a=6;
    }//GEN-LAST:event_RootActionPerformed

    
    
    
    //###################################################################################################################################################
    //***************************************************************************************************************************************************
    //          NUMBERS
    //---------------------------------------------------------------------------------------------------------------------------------------------------
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    
    
    
    
    
    
    
    private void one12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one12ActionPerformed
          //########One
        
        String one = display.getText();
        display.setText(one + "1");
        //Equalto.setText(Equalto.getText() +"1");
    }//GEN-LAST:event_one12ActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
        String one = display.getText();
        display.setText(one + "2");
        //Equalto.setText(Equalto.getText()+ "2");
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        String one = display.getText();
        display.setText(one + "3");
        //Equalto.setText(Equalto.getText()+ "3");
    }//GEN-LAST:event_ThreeActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        String one = display.getText();
        display.setText(one + "4");
        //Equalto.setText(Equalto.getText()+ "4");
    }//GEN-LAST:event_FourActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
        String one = display.getText();
        display.setText(one + "5");
        //Equalto.setText(Equalto.getText()+ "5");
    }//GEN-LAST:event_FiveActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
        String one = display.getText();
        display.setText(one + "6");
        //Equalto.setText(Equalto.getText()+ "6");
    }//GEN-LAST:event_SixActionPerformed

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        String one = display.getText();
        display.setText(one + "7");
        //Equalto.setText(Equalto.getText()+ "7");
    }//GEN-LAST:event_SevenActionPerformed

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightActionPerformed
        String one = display.getText();
        display.setText(one + "8");
        //Equalto.setText(Equalto.getText()+ "8");
    }//GEN-LAST:event_EightActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
        String one = display.getText();
        display.setText(one + "9");
        //Equalto.setText(Equalto.getText()+ "9");
    }//GEN-LAST:event_NineActionPerformed

    private void ClearscreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearscreenActionPerformed
        //String one = display.getText();
        display.setText("");
        
        
        
    }//GEN-LAST:event_ClearscreenActionPerformed

    private void PointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PointActionPerformed
        if(b1==0){
        String one = display.getText();
        b1=1;
        display.setText(one + ".");}
    }//GEN-LAST:event_PointActionPerformed

    private void SquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareActionPerformed
        
        firstnumber = display.getText();
        display.setText("");
        a=5;
        
    }//GEN-LAST:event_SquareActionPerformed

    private void DeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletActionPerformed

        firstnumber = display.getText();
        display.setText("");
        a=7;
        
        
        
    }//GEN-LAST:event_DeletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clearscreen;
    private javax.swing.JButton Delet;
    private javax.swing.JButton Devide;
    private javax.swing.JButton Eight;
    private javax.swing.JButton Equalto;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JButton Into;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Nine;
    private javax.swing.JButton Plus;
    private javax.swing.JButton Point;
    private javax.swing.JButton Root;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Six;
    private javax.swing.JButton Square;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton Zero;
    private javax.swing.JTextField display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton one12;
    // End of variables declaration//GEN-END:variables
}
